### ISSUE TITLE
esb version hard-coded in module folder and some config files

### ISSUE THREAD

**Issue by flaccid** [wso2/puppet-modules#2]
```
/etc/puppetlabs/puppet/modules/esb$ grep -R 4.8 ./*
./manifests/init.pp:# version            => '4.8.0',
./manifests/init.pp:  $version            = '4.8.0',
./templates/conf/carbon.xml.erb:    <Version>4.8.0</Version>
./templates/conf/axis2/axis2.xml.erb:    <parameter name="userAgent" locked="true">WSO2 ESB 4.8.0</parameter>
./templates/conf/axis2/axis2.xml.erb:    <parameter name="server" locked="true">WSO2 ESB 4.8.0</parameter>
```

The `init.pp` has a `$version` parameter that can be overridden to `4.8.1` for example, however the configuration files are hard-coded.  For some reason the module resides in esb / 4.8.0 / esb and there is no 4.8.1 but its a bad idea to have this fixed to begin with.

Version 4.8.0 is available at http://product-dist.wso2.com/products/enterprise-service-bus/4.8.0/wso2esb-4.8.0.zip however I would prefer to use 4.8.1.

**Comment by R-Rajkumar** [comment]
@flaccid We are in the process of refactoring all the puppet modules and we found your issue is addresses in the latest

**Comment by R-Rajkumar** [comment]
@flaccid We are in the process of refactoring all the puppet modules and we are no longer hard-coding product versions in any manifests/files. Please feel free to re-open this issue if you still find your issue is not addresses.
