### ISSUE TITLE
Remove hieradata and templates for older unused versions for products

### ISSUE THREAD

**Issue by chamilad** [wso2/puppet-modules#48]
Versions like GREG 4.6.0, IS 5.0.0, and BRS 2.1.0 are based on older Carbon platforms and are not likely to be used much. IMO we should deprecate these and remove them in a subsequent release.

**Comment by pubudu538** [comment]
This is completed with following commit ids.

0ea3a3085dec77b9a206fbafe19b9bed88186620
52427ef2accc58798850b5618f7c87d2fc3a6233
8ed73d812dd14390ebcae580efe7a733d313316d
a279c41da5a78a4b898a1bb5b517fb72afdae6aa
