### ISSUE TITLE
Metadata module names dont match class names

### ISSUE THREAD

**Issue by fatmcgav** [wso2/puppet-modules#79]
The value of 'name' in `metadata.json` should correspond to the class name in `init.pp`. 

Example of issue is: https://github.com/weareact/wso2puppet-modules/commit/2b97d7076051fdf3dc91d1885d7cb96b2b1af686

Suggest retaining the 'wso2' class prefix, as 'base' could likely conflict with local 'base' modules that people use.

**Comment by imesh** [comment]
Thanks @fatmcgav for reporting this! We have now fixed this with following commits:

https://github.com/wso2/puppet-modules/commit/8ac3d8466215f12be9b5484a923300cf296392b1
https://github.com/wso2/puppet-modules/commit/c3dc7291a327c6a43fa6f02b8415ffcd81083c82
